setwd('C:\\Users\\fedebayle\\Desktop\\Coursera\\Exploratory')
tab5rows <- read.table('household_power_consumption.txt', sep=';',dec='.',header = TRUE, nrows = 5)
classes <- sapply(tab5rows, class)
rawdata<-read.table('household_power_consumption.txt', sep=';',dec='.', header=TRUE,na.strings = "?", comment.char = "",colClasses=classes)
rawdata$Date<-as.Date(rawdata$Date, format="%d/%m/%Y")
data<-subset(rawdata,rawdata$Date>='2007-02-01' & rawdata$Date<='2007-02-02')
data$Datetime<-strptime(paste(data$Date, data$Time, sep=" "),'%Y-%m-%d %H:%M:%S')
#plot4
Sys.setlocale(locale = "C")
par(mfrow=c(2,2))
with(data,{
	plot(Datetime,Global_active_power, type='l', xlab="", ylab="Global Active Power")
	plot(Datetime,Voltage, type='l', xlab="datetime", ylab="Voltage")
	plot(Datetime,Sub_metering_1, type='l', col='black', xlab="", ylab="Energy sub metering")
	lines(Datetime, Sub_metering_2, col='red')
	lines(Datetime, Sub_metering_3, col='blue')
	legend("topright",cex=0.7, lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
	plot(Datetime,Global_reactive_power, type='l', xlab="datetime", ylab="Global_reactive_power", lwd=0.25)
dev.copy(png, file ="plot4.png", width=480, height=480)
dev.off()
})